apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boussole
resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - configmap.yaml
commonLabels:
  app.kubernetes.io/part-of: boussole
