"""
AssessmentReport: the serialised result the API returns and the UI renders.

This is a snapshot of AgentState plus assembly-time fields (status,
grounding_passed, failures). The fields mirror what the Next.js report view
and the eval harness consume; backward-compatible additions are fine,
renames are not.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from backend.agent.errors import TypedFailure
from backend.agent.state import (
    ClarificationQuestion,
    ClassificationResult,
    DraftedDocument,
    GapFinding,
    Obligation,
    RetrievedPassage,
    RunManifest,
    SystemProfile,
)


class ReportStatus(StrEnum):
    COMPLETE = "complete"
    INCOMPLETE_CLARIFICATION_EXHAUSTED = "incomplete_clarification_exhausted"
    FAILED = "failed"


class AssessmentReport(BaseModel):
    """The shape returned by /assess and consumed by the frontend."""

    model_config = ConfigDict(extra="forbid")

    run_id: str
    manifest: RunManifest
    status: ReportStatus
    grounding_passed: bool

    system_profile: SystemProfile
    classification: ClassificationResult | None
    clarification_questions: list[ClarificationQuestion] = Field(default_factory=list)
    clarification_iterations: int = 0

    obligations: list[Obligation] = Field(default_factory=list)
    gaps: list[GapFinding] = Field(default_factory=list)
    drafted_documents: list[DraftedDocument] = Field(default_factory=list)
    retrieved_passages: list[RetrievedPassage] = Field(default_factory=list)

    pre_assessment_notice: str = (
        "This is a technical pre-assessment generated by Boussole to support "
        "qualified legal review. It is not legal advice; every determination "
        "should be confirmed against the consolidated text of Regulation (EU) "
        "2024/1689 and signed off by counsel before being relied upon."
    )

    failures: list[TypedFailure] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
